//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhenFresh.Utilities.Testing.Unit.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("WhenFresh.Utilities.Testing.Unit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AbstractBaseClassTestException_Message {
            get {
                return ResourceManager.GetString("AbstractBaseClassTestException_Message", resourceCulture);
            }
        }
        
        internal static string AttributeUsage_AllowMultipleFalse {
            get {
                return ResourceManager.GetString("AttributeUsage_AllowMultipleFalse", resourceCulture);
            }
        }
        
        internal static string AttributeUsage_AllowMultipleTrue {
            get {
                return ResourceManager.GetString("AttributeUsage_AllowMultipleTrue", resourceCulture);
            }
        }
        
        internal static string AttributeUsage_InheritedFalse {
            get {
                return ResourceManager.GetString("AttributeUsage_InheritedFalse", resourceCulture);
            }
        }
        
        internal static string AttributeUsage_InheritedTrue {
            get {
                return ResourceManager.GetString("AttributeUsage_InheritedTrue", resourceCulture);
            }
        }
        
        internal static string AttributeUsage_ValidOn {
            get {
                return ResourceManager.GetString("AttributeUsage_ValidOn", resourceCulture);
            }
        }
        
        internal static string BaseClassTestException_Message {
            get {
                return ResourceManager.GetString("BaseClassTestException_Message", resourceCulture);
            }
        }
        
        internal static string ConcreteClassTestException_Message {
            get {
                return ResourceManager.GetString("ConcreteClassTestException_Message", resourceCulture);
            }
        }
        
        internal static string DecorationTestException_MissingMessage {
            get {
                return ResourceManager.GetString("DecorationTestException_MissingMessage", resourceCulture);
            }
        }
        
        internal static string DecorationTestException_UnexpectedMessage {
            get {
                return ResourceManager.GetString("DecorationTestException_UnexpectedMessage", resourceCulture);
            }
        }
        
        internal static string DefaultConstructorTestException_Message {
            get {
                return ResourceManager.GetString("DefaultConstructorTestException_Message", resourceCulture);
            }
        }
        
        internal static string ImplementationTestException_NoneMessage {
            get {
                return ResourceManager.GetString("ImplementationTestException_NoneMessage", resourceCulture);
            }
        }
        
        internal static string ImplementationTestException_UnexpectedMessage {
            get {
                return ResourceManager.GetString("ImplementationTestException_UnexpectedMessage", resourceCulture);
            }
        }
        
        internal static string Implements_IXmlSerializable {
            get {
                return ResourceManager.GetString("Implements_IXmlSerializable", resourceCulture);
            }
        }
        
        internal static string InterfaceTestException_Message {
            get {
                return ResourceManager.GetString("InterfaceTestException_Message", resourceCulture);
            }
        }
        
        internal static string PropertyExpectations_IsDecoratedWithXmlArray {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlArray", resourceCulture);
            }
        }
        
        internal static string PropertyExpectations_IsDecoratedWithXmlAttribute {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlAttribute", resourceCulture);
            }
        }
        
        internal static string PropertyExpectations_IsDecoratedWithXmlElement {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlElement", resourceCulture);
            }
        }
        
        internal static string PropertyExpectations_IsDecoratedWithXmlIgnore {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlIgnore", resourceCulture);
            }
        }
        
        internal static string PropertyExpectations_IsDecoratedWithXmlNamespaceDeclarations {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlNamespaceDeclarations", resourceCulture);
            }
        }
        
        internal static string PropertyExpectations_IsDecoratedWithXmlText {
            get {
                return ResourceManager.GetString("PropertyExpectations_IsDecoratedWithXmlText", resourceCulture);
            }
        }
        
        internal static string PropertyGetterTestException_Message {
            get {
                return ResourceManager.GetString("PropertyGetterTestException_Message", resourceCulture);
            }
        }
        
        internal static string PropertyGetterTestOfTException_Message {
            get {
                return ResourceManager.GetString("PropertyGetterTestOfTException_Message", resourceCulture);
            }
        }
        
        internal static string PropertySetterTestException_Message {
            get {
                return ResourceManager.GetString("PropertySetterTestException_Message", resourceCulture);
            }
        }
        
        internal static string SealedClassTestException_SealedMessage {
            get {
                return ResourceManager.GetString("SealedClassTestException_SealedMessage", resourceCulture);
            }
        }
        
        internal static string SealedClassTestException_UnsealedMessage {
            get {
                return ResourceManager.GetString("SealedClassTestException_UnsealedMessage", resourceCulture);
            }
        }
        
        internal static string TypeExpectationsException_InterfaceMessage {
            get {
                return ResourceManager.GetString("TypeExpectationsException_InterfaceMessage", resourceCulture);
            }
        }
        
        internal static string TypeExpectations_IsDecoratedWithAttributeUsage {
            get {
                return ResourceManager.GetString("TypeExpectations_IsDecoratedWithAttributeUsage", resourceCulture);
            }
        }
        
        internal static string TypeExpectations_IsDecoratedWithSerializable {
            get {
                return ResourceManager.GetString("TypeExpectations_IsDecoratedWithSerializable", resourceCulture);
            }
        }
        
        internal static string TypeExpectations_IsDecoratedWithXmlRoot {
            get {
                return ResourceManager.GetString("TypeExpectations_IsDecoratedWithXmlRoot", resourceCulture);
            }
        }
        
        internal static string ValueTypeTestException_Message {
            get {
                return ResourceManager.GetString("ValueTypeTestException_Message", resourceCulture);
            }
        }
        
        internal static string XmlArrayDecorationTestException_Message1 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message1", resourceCulture);
            }
        }
        
        internal static string XmlArrayDecorationTestException_Message2 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message2", resourceCulture);
            }
        }
        
        internal static string XmlArrayDecorationTestException_Message3 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message3", resourceCulture);
            }
        }
        
        internal static string XmlArrayDecorationTestException_Message4 {
            get {
                return ResourceManager.GetString("XmlArrayDecorationTestException_Message4", resourceCulture);
            }
        }
        
        internal static string XmlAttributeDecorationTestException_Message1 {
            get {
                return ResourceManager.GetString("XmlAttributeDecorationTestException_Message1", resourceCulture);
            }
        }
        
        internal static string XmlAttributeDecorationTestException_Message2 {
            get {
                return ResourceManager.GetString("XmlAttributeDecorationTestException_Message2", resourceCulture);
            }
        }
        
        internal static string XmlAttributeDecorationTestException_Message3 {
            get {
                return ResourceManager.GetString("XmlAttributeDecorationTestException_Message3", resourceCulture);
            }
        }
        
        internal static string XmlElementDecorationTestException_Message1 {
            get {
                return ResourceManager.GetString("XmlElementDecorationTestException_Message1", resourceCulture);
            }
        }
        
        internal static string XmlElementDecorationTestException_Message2 {
            get {
                return ResourceManager.GetString("XmlElementDecorationTestException_Message2", resourceCulture);
            }
        }
        
        internal static string XmlElementDecorationTestException_Message3 {
            get {
                return ResourceManager.GetString("XmlElementDecorationTestException_Message3", resourceCulture);
            }
        }
        
        internal static string XmlIgnoreDecorationTestException_Message {
            get {
                return ResourceManager.GetString("XmlIgnoreDecorationTestException_Message", resourceCulture);
            }
        }
        
        internal static string XmlNamespaceDeclarationsDecorationTestException_Message {
            get {
                return ResourceManager.GetString("XmlNamespaceDeclarationsDecorationTestException_Message", resourceCulture);
            }
        }
        
        internal static string XmlRootDecorationTestException_NameMessage {
            get {
                return ResourceManager.GetString("XmlRootDecorationTestException_NameMessage", resourceCulture);
            }
        }
        
        internal static string XmlRootDecorationTestException_NamespaceMessage {
            get {
                return ResourceManager.GetString("XmlRootDecorationTestException_NamespaceMessage", resourceCulture);
            }
        }
        
        internal static string XmlRootDecorationTestException_UndecoratedMessage {
            get {
                return ResourceManager.GetString("XmlRootDecorationTestException_UndecoratedMessage", resourceCulture);
            }
        }
        
        internal static string XmlSerialization_EqualsNew {
            get {
                return ResourceManager.GetString("XmlSerialization_EqualsNew", resourceCulture);
            }
        }
        
        internal static string XmlSerialization_GetSchema {
            get {
                return ResourceManager.GetString("XmlSerialization_GetSchema", resourceCulture);
            }
        }
        
        internal static string XmlSerialization_ReadXmlNull {
            get {
                return ResourceManager.GetString("XmlSerialization_ReadXmlNull", resourceCulture);
            }
        }
        
        internal static string XmlSerialization_WriteXmlNull {
            get {
                return ResourceManager.GetString("XmlSerialization_WriteXmlNull", resourceCulture);
            }
        }
        
        internal static string XmlTextDecorationTestException_Message {
            get {
                return ResourceManager.GetString("XmlTextDecorationTestException_Message", resourceCulture);
            }
        }
    }
}
